### ISSUE TITLE
VS2019 support

### ISSUE THREAD

**Issue by mniak** [CodingWithCalvin/VS-OpenInNotepadPlusPlus#1]
Please, add!

**Comment by mniak** [comment]
I forked you this repository, considering to make a PR.
But it occurs that this is already compatible with VS2019. Great job!
It only is not listed in the Visual Studio marketplace.

Please, publish the newest version there.
Thanks!

By the way, this extension is very nice an useful!

**Comment by CalvinAllen** [comment]
Hi, @mniak, thanks for the comments!  I will get a new version published that will support 2019.  Thanks again!
