### ISSUE TITLE
Open in Notepad++ has no effect in VS 2015

### ISSUE THREAD

**Issue by manu-st** [CodingWithCalvin/VS-OpenInNotepadPlusPlus#3]
Hi,

With 3.0.4, when I choose Open in Notepad++, it doesn't do anything. Not sure what to look for to help debugging this issue. Anything that I should provide to help figure out what could be wrong?

Thanks,
Manu

**Comment by CalvinAllen** [comment]
Thanks for reporting, @manu-st .

I don't have VS2015 installed anymore, and I was hoping making the necessary changes from our previous issue is all it would take.  

I can see now, I'm going to need to install 2015 again to dig into this, so I'll get started on that, and get back to you ASAP.

**Comment by CalvinAllen** [comment]
@manu-st I believe I have this resolved.  There were even more 2017 references hanging around (even though the *name* of the package indicates a lower version).  

I have 2015, 2017, and 2019 installed, and was able to successfully utilize it in all three.

Please let me know if you run into anything else, and I appreciate your patience!
