### ISSUE TITLE
VS2022

### ISSUE THREAD

**Issue by OzBob** [CodingWithCalvin/VS-OpenInNotepadPlusPlus#6]
https://marketplace.visualstudio.com/items?itemName=CalvinAAllen.OpeninNotepad

add support in VSIX for VS2022

**Comment by CalvinAllen** [comment]
Working on it, just need to make some final tweaks and get it deployed to the marketplace.  Probably another 2-3 days.

**Comment by OzBob** [comment]
i was going to manually unzip to vsix file and add ,18.0 to the manifest. or should i wait till you are done?

**Comment by CalvinAllen** [comment]
I'm honestly not even sure it will work.  With the move to 64bit by VS, I've had to make quite a few other changes as well.

You might have better luck, if you're interested, by grabbing the VS2022 branch and compiling it, and then use that VSIX.

**Comment by OzBob** [comment]
yep, certainly not as simple as adding vs2019 support.

https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

I'll leave it with you. Also, great job! and Thanks!

**Comment by CalvinAllen** [comment]
Yeah, it's a bit of a pain, but once it's done, should be good to go for years :)

Thanks for the kind words, I appreciate it!

**Comment by CalvinAllen** [comment]
@OzBob New version is out; let me know if you run into any issues!

**Comment by OzBob** [comment]
installed: VS2022 ext and works just fine.
https://marketplace.visualstudio.com/items?itemName=CalvinAAllen.OpenInNotepadPP2022
